### ISSUE TITLE
The update to V1.3 caused the crash

### ISSUE THREAD

**Issue by mcmso** [FalsePattern/AnimFix#2]
https://paste.ubuntu.com/p/2HsBNDgbND/
I don't know what happened, if you need any more information please reply to me

**Comment by FalsePattern** [comment]
I managed to reproduce this issue locally, it looks like FastCraft disables some of its code my mod was expecting when used with older versions of OptiFine.

Fixed in 1.3.1

**Comment by mcmso** [comment]
> I managed to reproduce this issue locally, it looks like FastCraft disables some of its code my mod was expecting when used with older versions of OptiFine.
> 
> Fixed in 1.3.1

I updated to V1.3.1 but still crashed

I'm really sad
https://paste.ubuntu.com/p/fJwkrvYtRw/

**Comment by FalsePattern** [comment]
Please also include the fml-client-latest.log file, the crashlog contains no relevant information.

**Comment by mcmso** [comment]
[fml-client-latest.log](https://github.com/FalsePattern/AnimFix/files/8359406/fml-client-latest.log)


> Please also include the fml-client-latest.log file, the crashlog contains no relevant information.

**Comment by FalsePattern** [comment]
Should be fixed in 1.3.3
